
---
# Pod1
apiVersion: v1
kind:       Pod
metadata:
  name: iconoflix1
  labels:
    app: iconoflix
spec:
  containers:
  - name:  iconoflix
    image: quay.io/imhotepio/iconoflix:mem
    ports:
    - name:          api
      containerPort: 4000
---
# Pod2
apiVersion: v1
kind:       Pod
metadata:
  name: iconoflix2
  labels:
    app: iconoflix
spec:
  containers:
  - name:  iconoflix
    image: quay.io/imhotepio/iconoflix:mem
    ports:
    - name:          api
      containerPort: 4000
---
# Service
kind: Service
apiVersion: v1
metadata:
  name: iconoflix
  labels:
    app: iconoflix
spec:
  type:  NodePort
  selector:
    app: iconoflix
  ports:
    - name:       api
      port:       4000
      targetPort: api
      nodePort:   30500
