# Service
kind: Service
apiVersion: v1
metadata:
  name: iconoflix
  labels:
    app: iconoflix
spec:
  type: NodePort
  selector:
    app: iconoflix
  ports:
    - name: api
      port: 4000
      targetPort: api
      nodePort: 30400
