replicaCount: 1

image:
  pullPolicy: Always

service:
  type: NodePort
  nodePort: 30401

db:
  host: icx-db-postgresql
  port: 5432
  secret: icx-db-postgresql
  pwd_key: postgresql-password
  user: postgres
  name: iconoflix
